# Generated by Django 5.1.7 on 2025-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoprocessing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='videoprocessing',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videoprocessing',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoprocessing',
            name='username',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
