# Generated by Django 5.1.7 on 2025-04-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_api', '0002_alter_videoprocessing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocessing',
            name='cloudinary_urls_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoprocessing',
            name='num_shorts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
