# Generated by Django 5.1.7 on 2025-04-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_api', '0003_videoprocessing_cloudinary_urls_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocessing',
            name='add_captions',
            field=models.BooleanField(default=True),
        ),
    ]
