# Generated by Django 5.1.7 on 2025-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_api', '0004_videoprocessing_add_captions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageDubbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='anonymous', max_length=100)),
                ('video_url', models.URLField(help_text='URL of the video to be dubbed')),
                ('source_language', models.CharField(default='English', max_length=50)),
                ('target_language', models.CharField(default='Hindi', max_length=50)),
                ('voice', models.CharField(choices=[('alloy', 'Alloy'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('shimmer', 'Shimmer')], default='alloy', max_length=20)),
                ('original_video_path', models.CharField(blank=True, max_length=512, null=True)),
                ('dubbed_video_path', models.CharField(blank=True, max_length=512, null=True)),
                ('cloudinary_url', models.URLField(blank=True, null=True)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cloudinary_urls_json', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('add_captions', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
