version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./client
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./client:/app
#     environment:
#       - NODE_ENV=development

#   backend:
#     build:
#       context: ./server
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./server:/app
#     environment:
#       - DEBUG=True
